-rwxr-xr-x 1 root root 383 Jul 28 2013 var/lib/dpkg/info/debianutils.postinst

#! /bin/sh -e

if test -z "$2" && test ! -f /etc/shells
then
        cp -p /usr/share/debianutils/shells /etc/shells
fi

case "$1" in
    configure)
    if which update-mime >/dev/null;
    then
	    update-mime
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
