-rw-r--r-- 1 root root 628 May 23 23:12 usr/share/perl/5.20.2/unicore/lib/Gc/Nl.pl

# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.3.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V24
5870
5873
8544
8579
8581
8585
12295
12296
12321
12330
12344
12347
42726
42736
65856
65909
66369
66370
66378
66379
66513
66518
74752
74851
END
