-rw-r--r-- 1 root root 552 May 23 23:12 usr/share/perl/5.20.2/unicore/lib/Sc/Armn.pl

# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.3.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V12
1329
1367
1369
1376
1377
1416
1418
1419
1423
1424
64275
64280
END
