-rw-r--r-- 1 root root 592 May 23 23:12 usr/share/perl/5.20.2/unicore/lib/Sc/Hebr.pl

# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.3.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V18
1425
1480
1488
1515
1520
1525
64285
64311
64312
64317
64318
64319
64320
64322
64323
64325
64326
64336
END
